name = "Cobblemon Careca"
author = "Felipe Malicheski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdcb010ffb0f73d76f7a055120bc7fe306ea5c426069021c203094522ab60a11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.146"
